apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/server-snippet: |-
      location /jobs {
        return 302 https://angel.co/company/subsquid/jobs;
      }
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.landing.api.basePath }}
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: static
                port:
                  number: 3000
{{- if .Values.ingress.wwwRedirect }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-www-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/server-snippet: |-
      location ~ / {
        rewrite / https://{{ .Values.ingress.host }}$request_uri permanent;
      }
spec:
  rules:
    - host: www.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: static
                port:
                  name: http
{{- end}}
